# Generated by Django 6.0.3 on 2026-03-14 09:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Scope",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "internal_base_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ref_code", models.CharField(blank=True, max_length=255, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "value",
                    models.CharField(
                        help_text='Machine-readable scope, e.g. "read:logs"',
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text='Human-readable label, e.g. "Read Logs"',
                        max_length=128,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text='Endpoint hint, e.g. "GET /api/logs/"',
                        max_length=256,
                    ),
                ),
            ],
            options={
                "ordering": ["value"],
            },
        ),
    ]
