# Generated by Django 6.0.3 on 2026-03-14 15:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("system", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecycleBin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Recycle Bin",
                "verbose_name_plural": "Recycle Bin",
            },
        ),
        migrations.CreateModel(
            name="RecycleBinItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_uuid", models.UUIDField(db_index=True)),
                (
                    "object_repr",
                    models.CharField(
                        help_text="Snapshot of str(instance) at deletion time, so the item is identifiable even if the object is later hard-deleted.",
                        max_length=255,
                    ),
                ),
                (
                    "model_label",
                    models.CharField(
                        help_text='app_label.ModelName, e.g. "staff.Staff"',
                        max_length=255,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "bin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="system.recyclebin",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who triggered the soft-delete, if available.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recycled_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Recycle Bin Item",
                "verbose_name_plural": "Recycle Bin Items",
                "ordering": ["-deleted_at"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_uuid"],
                        name="system_recy_content_414ba5_idx",
                    )
                ],
            },
        ),
    ]
