# Generated by Django 6.0.3 on 2026-03-14 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_mgt", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="apikeyrequestlog",
            options={
                "ordering": ["-requested_at"],
                "verbose_name": "API Key Request Log",
                "verbose_name_plural": "API Key Request Logs",
            },
        ),
    ]
