# Generated by Django 6.0.3 on 2026-03-15 08:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("staff", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Fingerprint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "internal_base_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ref_code", models.CharField(blank=True, max_length=255, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "slot",
                    models.PositiveSmallIntegerField(
                        help_text="Scanner hardware slot index (0-1000)."
                    ),
                ),
                (
                    "finger_index",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Right Thumb"),
                            (1, "Right Index"),
                            (2, "Right Middle"),
                            (3, "Right Ring"),
                            (4, "Right Little"),
                            (5, "Left Thumb"),
                            (6, "Left Index"),
                            (7, "Left Middle"),
                            (8, "Left Ring"),
                            (9, "Left Little"),
                        ],
                        help_text="Which finger (0 = right thumb … 9 = left little).",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Optional label for this fingerprint (e.g. 'Work Scanner').",
                        max_length=100,
                    ),
                ),
                ("enrolled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "enrolled_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin user who performed the enrollment.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enrollments_performed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fingerprint_entries",
                        to="staff.staff",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fingerprint",
                "verbose_name_plural": "Fingerprints",
                "ordering": ["slot", "staff__full_name", "finger_index"],
            },
        ),
        migrations.CreateModel(
            name="AccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "internal_base_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ref_code", models.CharField(blank=True, max_length=255, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "result",
                    models.CharField(
                        choices=[("granted", "Granted"), ("denied", "Denied")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                (
                    "deny_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("no_fingerprint_match", "No Fingerprint Match"),
                            ("outside_allowed_hours", "Outside Allowed Hours"),
                            ("outside_allowed_days", "Outside Allowed Days"),
                            ("access_revoked", "Access Revoked"),
                            ("inactive_staff", "Inactive Staff"),
                            ("locked_out", "Locked Out"),
                            ("permission_expired", "Permission Expired"),
                        ],
                        default="",
                        help_text="Populated only when result is denied.",
                        max_length=30,
                    ),
                ),
                (
                    "confidence",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Match confidence score from the scanner (0–100).",
                    ),
                ),
                (
                    "scanner_slot",
                    models.SmallIntegerField(
                        blank=True,
                        help_text="Hardware slot index that triggered this event.",
                        null=True,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When the scan occurred (set by the daemon, not auto_now_add).",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null when the fingerprint did not match anyone.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="access_logs",
                        to="staff.staff",
                    ),
                ),
                (
                    "fingerprint",
                    models.ForeignKey(
                        blank=True,
                        help_text="The specific fingerprint template that was matched.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="access_logs",
                        to="fingerprints.fingerprint",
                    ),
                ),
            ],
            options={
                "verbose_name": "Access Log",
                "verbose_name_plural": "Access Logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddConstraint(
            model_name="fingerprint",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("staff", "finger_index"),
                name="unique_active_finger_per_staff",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="fingerprint",
            unique_together={("slot",)},
        ),
        migrations.AddIndex(
            model_name="accesslog",
            index=models.Index(
                fields=["-timestamp"], name="fingerprint_timesta_7a8873_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accesslog",
            index=models.Index(
                fields=["staff", "-timestamp"], name="fingerprint_staff_i_1861b0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accesslog",
            index=models.Index(
                fields=["result", "-timestamp"], name="fingerprint_result_1106fa_idx"
            ),
        ),
    ]
