# Generated by Django 6.0.3 on 2026-06-03 19:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fingerprints", "0001_initial"),
        ("staff", "0004_accesspermission_alter_department_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="fingerprint",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="accesslog",
            name="deny_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("no_fingerprint_match", "No Fingerprint Match"),
                    ("outside_allowed_hours", "Outside Allowed Hours"),
                    ("outside_allowed_days", "Outside Allowed Days"),
                    ("access_revoked", "Access Revoked"),
                    ("inactive_staff", "Inactive Staff"),
                    ("locked_out", "Locked Out"),
                    ("permission_expired", "Permission Expired"),
                    ("no_active_permission", "No Active Permission"),
                    ("permission_not_yet_valid", "Permission Not Yet Valid"),
                    ("scanner_error", "Scanner Error"),
                ],
                default="",
                help_text="Populated only when result is denied.",
                max_length=30,
            ),
        ),
        migrations.AddConstraint(
            model_name="fingerprint",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("slot",),
                name="unique_active_fingerprint_slot",
            ),
        ),
    ]
