# Generated by Django 6.0.3 on 2026-03-15 08:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fingerprints", "0001_initial"),
        ("staff", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="staff",
            options={
                "ordering": ["full_name"],
                "verbose_name": "Staff Member",
                "verbose_name_plural": "Staff Members",
            },
        ),
        migrations.AddField(
            model_name="staff",
            name="user",
            field=models.OneToOneField(
                blank=True,
                help_text="System login account for this person. May be null.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="StaffFingerprint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "internal_base_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ref_code", models.CharField(blank=True, max_length=255, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("label", models.CharField(blank=True, default="", max_length=50)),
                (
                    "fingerprint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_fingerprints",
                        to="fingerprints.fingerprint",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_fingerprints",
                        to="staff.staff",
                    ),
                ),
            ],
            options={
                "verbose_name": "Staff Fingerprint",
                "verbose_name_plural": "Staff Fingerprints",
            },
        ),
        migrations.AddField(
            model_name="staff",
            name="fingerprints",
            field=models.ManyToManyField(
                blank=True,
                related_name="assigned_staff",
                through="staff.StaffFingerprint",
                to="fingerprints.fingerprint",
            ),
        ),
        migrations.AddConstraint(
            model_name="stafffingerprint",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("staff", "fingerprint"),
                name="unique_active_staff_fingerprint",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="stafffingerprint",
            unique_together={("fingerprint",)},
        ),
    ]
