# Generated by Django 6.0.3 on 2026-03-15 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0002_alter_staff_options_staff_user_stafffingerprint_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stafffingerprint",
            name="label",
        ),
    ]
