# Generated by Django 6.0.3 on 2026-04-25 17:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0003_remove_stafffingerprint_label"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "internal_base_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ref_code", models.CharField(blank=True, max_length=255, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "is_allowed",
                    models.BooleanField(
                        default=True,
                        help_text="Master on/off switch. False = always denied regardless of schedule.",
                    ),
                ),
                (
                    "access_start_time",
                    models.TimeField(
                        blank=True,
                        help_text="Earliest time of day entry is allowed (e.g. 08:00).",
                        null=True,
                    ),
                ),
                (
                    "access_end_time",
                    models.TimeField(
                        blank=True,
                        help_text="Latest time of day entry is allowed (e.g. 18:00).",
                        null=True,
                    ),
                ),
                (
                    "allowed_days",
                    models.CharField(
                        blank=True,
                        default="0,1,2,3,4",
                        help_text="Comma-separated day indices (0=Mon … 6=Sun). Empty = all days.",
                        max_length=20,
                    ),
                ),
                (
                    "valid_from",
                    models.DateField(
                        blank=True,
                        help_text="Permission becomes active on this date.",
                        null=True,
                    ),
                ),
                (
                    "valid_until",
                    models.DateField(
                        blank=True,
                        help_text="Permission expires after this date.",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Access Permission",
                "verbose_name_plural": "Access Permissions",
            },
        ),
        migrations.AlterModelOptions(
            name="department",
            options={},
        ),
        migrations.AlterField(
            model_name="department",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name="department",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("name",),
                name="unique_active_department_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="role",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("name",),
                name="unique_active_role_name",
            ),
        ),
        migrations.AddField(
            model_name="accesspermission",
            name="staff",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="access_permission",
                to="staff.staff",
            ),
        ),
    ]
