# Generated by Django 6.0.3 on 2026-03-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DeviceSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        default="1234567890",
                        editable=False,
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "device_model",
                    models.CharField(
                        default="BAIFAM-ModelX", editable=False, max_length=255
                    ),
                ),
                (
                    "hardware_version",
                    models.CharField(default="1.0", editable=False, max_length=255),
                ),
                (
                    "firmware_version",
                    models.CharField(default="1.0.0", editable=False, max_length=255),
                ),
            ],
            options={
                "verbose_name": "Device Setting",
                "verbose_name_plural": "Device Settings",
            },
        ),
    ]
