# Generated by Django 6.0.3 on 2026-03-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="devicesettings",
            name="device_location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="devicesettings",
            name="device_name",
            field=models.CharField(default="BAIFAM Device", max_length=255),
        ),
    ]
