# Generated by Django 6.0.3 on 2026-03-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0002_devicesettings_device_location_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devicesettings",
            name="hardware_version",
            field=models.CharField(default="1.1", editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name="devicesettings",
            name="serial_number",
            field=models.CharField(
                default="SN1234567890", editable=False, max_length=255, unique=True
            ),
        ),
    ]
