# Generated by Django 6.0.3 on 2026-03-12 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0003_alter_devicesettings_hardware_version_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devicesettings",
            name="device_model",
            field=models.CharField(editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name="devicesettings",
            name="firmware_version",
            field=models.CharField(editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name="devicesettings",
            name="hardware_version",
            field=models.CharField(editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name="devicesettings",
            name="serial_number",
            field=models.CharField(editable=False, max_length=255, unique=True),
        ),
    ]
