# Generated by Django 6.0.3 on 2026-03-12 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0004_alter_devicesettings_device_model_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="devicesettings",
            name="allow_unknown_finger_log",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="devicesettings",
            name="buzzer_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="devicesettings",
            name="buzzer_volume",
            field=models.PositiveSmallIntegerField(default=80),
        ),
        migrations.AddField(
            model_name="devicesettings",
            name="lockout_duration_mins",
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name="devicesettings",
            name="max_duration_before_sleep_if_idle",
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name="devicesettings",
            name="max_failed_attempts",
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name="devicesettings",
            name="require_2finger_confirm",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="devicesettings",
            name="timezone",
            field=models.CharField(default="UTC", max_length=120),
        ),
        migrations.AddField(
            model_name="devicesettings",
            name="unlock_duration_sec",
            field=models.PositiveSmallIntegerField(default=80),
        ),
    ]
