# Generated by Django 6.0.3 on 2026-03-15 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0006_alter_devicesettings_buzzer_volume_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="devicesettings",
            name="fingerprint_template_size",
            field=models.PositiveSmallIntegerField(default=1000, editable=False),
        ),
        migrations.AddField(
            model_name="devicesettings",
            name="max_fingerprints_per_staff",
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
